
version: '{build}'

build: off

environment:
  matrix:

    - PYTHON: "C:/Python35"
      TOXENV: "py35"

    - PYTHON: "C:/Python36"
      TOXENV: "py36"

    - PYTHON: "C:/Python37"
      TOXENV: "py37"

    - PYTHON: "C:/Python38"
      TOXENV: "py38"

    - PYTHON: "C:/Python39"
      TOXENV: "py39"

init:
  - "ECHO %TOXENV%"
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

install:
  - "%PYTHON%/python.exe -m pip install -U wheel pip setuptools virtualenv"
  - "%PYTHON%/python.exe -m pip install tox mercurial"
  - "%PYTHON%/python.exe -m pip install -e ."

  - 'git config --global user.email "bumpversion-test-git@appveyor.ci"'
  - 'git config --global user.name "Testing Git on AppVeyor CI"'
  - 'git --version'
  - 'git config --list'

  - ps: Add-Content $ENV:UserProfile\Mercurial.ini "[ui]`r`nusername = Testing Mercurial on AppVeyor CI <bumpversion-test-hg@appveyor.ci>"
  - ps: Write-Host $ENV:UserProfile\Mercurial.ini
  - ps: Get-Content $ENV:UserProfile\Mercurial.ini
  - 'hg --version'

test_script:
  - "%PYTHON%/python.exe -m pip --version"
  - "%PYTHON%/Scripts/virtualenv.exe --version"
  - "%PYTHON%/python.exe -m pip --version"
  - "%PYTHON%/python.exe -m pip -- -v"
